#!/usr/bin/env bash
# Run the fog_prob / mixed-intensity sweep (configs/sweep/*.yaml, generated by
# gen_sweep_configs.py) sequentially on the current machine — the local-machine
# counterpart to scripts/slurm/submit_sweep.sh, for environments where sbatch
# isn't on PATH (e.g. an interactive HPC shell without SLURM client tools).
#
# Each config is trained then evaluated on ACDC fog val before moving to the
# next (rather than all-train-then-all-eval) so results/summary.md has
# meaningful partial results throughout a multi-day run.
#
# Usage:
#   python scripts/gen_sweep_configs.py   # regenerate configs/sweep/ if needed
#   bash scripts/run_sweep.sh
#
# Idempotent/resumable: already-complete experiments are skipped, partial ones
# resume from latest.pth — safe to re-run after an interruption.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

source /home/taah3149/Documents/Group_Studies/.venv/bin/activate

ACDC_ROOT="/home/taah3149/Documents/Group_Studies/dataset/acdc"

shopt -s nullglob
CONFIGS=(configs/sweep/*.yaml)
shopt -u nullglob

if [[ ${#CONFIGS[@]} -eq 0 ]]; then
  echo "No configs found in configs/sweep/ — run: python scripts/gen_sweep_configs.py"
  exit 1
fi

echo "=== Fog Mixing Sweep (fog_prob / mixed intensity) ==="
echo "Timestamp: $(date)"
echo "Configs: ${#CONFIGS[@]}"
echo "(idempotent: already-complete experiments are skipped, partial ones resume from latest.pth)"

for cfg in "${CONFIGS[@]}"; do
  name=$(python -c "import yaml; print(yaml.safe_load(open('$cfg'))['experiment']['name'])")
  out_dir="results/$name"
  log="$out_dir/train.log"
  latest="$out_dir/latest.pth"
  eval_json="$out_dir/acdc_eval.json"

  echo ""
  if [[ -f "$eval_json" ]] || { [[ -f "$out_dir/best.pth" ]] && grep -q "Training complete" "$log" 2>/dev/null; }; then
    echo ">>> Skipping train (already complete): $name"
  elif [[ -f "$latest" ]]; then
    echo ">>> Resuming: $name (from $latest)"
    python src/train.py --config "$cfg" --resume "$latest"
  else
    echo ">>> Training (fresh start): $name"
    python src/train.py --config "$cfg"
  fi

  if [[ -f "$eval_json" ]]; then
    echo ">>> Skipping eval (already done): $name"
  else
    echo ">>> Evaluating: $name"
    python src/evaluate.py \
      --config "$cfg" \
      --checkpoint "$out_dir/best.pth" \
      --acdc-root "$ACDC_ROOT" \
      --output "$eval_json"
  fi

  echo ">>> Done: $name"
  python scripts/compile_results.py > /dev/null   # keep summary.md fresh throughout
done

echo ""
echo "=== Sweep complete. Final results table: ==="
python scripts/compile_results.py
