#!/usr/bin/env bash
# Resweep of configs/sweep_mitb2/*.yaml (generated by gen_mitb2_configs.py) —
# identical fog_prob/mixed matrix as the original resnet101 sweep, but with
# encoder_name=mit_b2, architecture=fpn. Follow-up to the backbone POC
# (see results/poc_run.log) which found mit_b2/FPN beats resnet101/DeepLabV3+
# by +13% to +23% relative mIoU on ACDC fog at matched epochs.
#
# Usage:
#   python scripts/gen_mitb2_configs.py   # regenerate configs/sweep_mitb2/ if needed
#   bash scripts/run_sweep_mitb2.sh
#
# Idempotent/resumable: already-complete experiments are skipped, partial ones
# resume from latest.pth — safe to re-run after an interruption.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

source /home/taah3149/Documents/Group_Studies/.venv/bin/activate

ACDC_ROOT="/home/taah3149/Documents/Group_Studies/dataset/acdc"

shopt -s nullglob
CONFIGS=(configs/sweep_mitb2/*.yaml)
shopt -u nullglob

if [[ ${#CONFIGS[@]} -eq 0 ]]; then
  echo "No configs found in configs/sweep_mitb2/ — run: python scripts/gen_mitb2_configs.py"
  exit 1
fi

echo "=== mit_b2/FPN Backbone Resweep ==="
echo "Timestamp: $(date)"
echo "Configs: ${#CONFIGS[@]}"
echo "(idempotent: already-complete experiments are skipped, partial ones resume from latest.pth)"

for cfg in "${CONFIGS[@]}"; do
  name=$(python -c "import yaml; print(yaml.safe_load(open('$cfg'))['experiment']['name'])")
  out_dir=$(python -c "import yaml; print(yaml.safe_load(open('$cfg'))['training']['output_dir'])")
  log="$out_dir/train.log"
  latest="$out_dir/latest.pth"
  eval_json="$out_dir/acdc_eval.json"

  echo ""
  if [[ -f "$eval_json" ]] || { [[ -f "$out_dir/best.pth" ]] && grep -q "Training complete" "$log" 2>/dev/null; }; then
    echo ">>> Skipping train (already complete): $name"
  elif [[ -f "$latest" ]]; then
    echo ">>> Resuming: $name (from $latest)"
    python src/train.py --config "$cfg" --resume "$latest"
  else
    echo ">>> Training (fresh start): $name"
    python src/train.py --config "$cfg"
  fi

  if [[ -f "$eval_json" ]]; then
    echo ">>> Skipping eval (already done): $name"
  else
    echo ">>> Evaluating: $name"
    python src/evaluate.py \
      --config "$cfg" \
      --checkpoint "$out_dir/best.pth" \
      --acdc-root "$ACDC_ROOT" \
      --output "$eval_json"
  fi

  echo ">>> Done: $name"
  python scripts/compile_results.py > /dev/null   # keep summary.md fresh throughout
done

echo ""
echo "=== mit_b2 resweep complete. Final results table: ==="
python scripts/compile_results.py
