#!/usr/bin/env bash
# Submit all fog_prob / mixed-intensity sweep configs (configs/sweep/*.yaml,
# generated by scripts/gen_sweep_configs.py) as SLURM jobs. Each train job is
# chained to an evaluate job via --dependency=afterok, so ACDC eval runs
# automatically the moment training finishes — no need to babysit the queue.
#
# Usage:
#   python scripts/gen_sweep_configs.py   # regenerate configs/sweep/ if needed
#   bash scripts/slurm/submit_sweep.sh
#
# Single-GPU cluster: jobs queue sequentially, expect this to take multiple
# days for the full 23-run sweep. Check progress with: squeue -u $USER

set -euo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

ACDC_ROOT="/home/taah3149/Documents/Group_Studies/dataset/acdc"

mkdir -p results/slurm_logs

shopt -s nullglob
configs=(configs/sweep/*.yaml)
shopt -u nullglob

if [[ ${#configs[@]} -eq 0 ]]; then
  echo "No configs found in configs/sweep/ — run: python scripts/gen_sweep_configs.py"
  exit 1
fi

echo "Submitting ${#configs[@]} sweep experiments..."

for cfg in "${configs[@]}"; do
  name=$(python -c "import yaml; c=yaml.safe_load(open('$cfg')); print(c['experiment']['name'])")

  train_jid=$(sbatch --export=CONFIG="$cfg" --job-name="fog_${name}" scripts/slurm/train.slurm | awk '{print $NF}')
  echo "Submitted train  $name  → job $train_jid"

  eval_jid=$(sbatch \
    --dependency=afterok:"$train_jid" \
    --export=CONFIG="$cfg",CHECKPOINT="results/${name}/best.pth",ACDC_ROOT="$ACDC_ROOT" \
    --job-name="fogeval_${name}" \
    scripts/slurm/evaluate.slurm | awk '{print $NF}')
  echo "  chained eval   $name  → job $eval_jid (after $train_jid)"
done

echo ""
echo "All submitted. Monitor with: squeue -u \$USER"
echo "Once all finish, run: python scripts/compile_results.py"
